#!/bin/bash
# Evaluate Tool Script
# Uso: ./evaluate_tool.sh "Nombre de la Herramienta" "descripción" "workflow"
# Imprime el template de evaluación para que CloudCode lo complete

TOOL_NAME="${1:-Herramienta Sin Nombre}"
TOOL_DESC="${2:-descripción pendiente}"
WORKFLOW="${3:-por_definir}"
DATE=$(date +%Y-%m-%d)
ID="EVAL-$(date +%Y%m%d)-$(echo $TOOL_NAME | tr ' ' '_' | tr '[:upper:]' '[:lower:]')"

echo ""
echo "════════════════════════════════════════════════════"
echo "  EVALUACIÓN DE HERRAMIENTA — Hansel-OS"
echo "════════════════════════════════════════════════════"
echo ""
echo "ID: $ID"
echo "Herramienta: $TOOL_NAME"
echo "Fecha: $DATE"
echo ""
echo "────────────────────────────────────────────────────"
echo "  TEST DE LOS 7 CRITERIOS"
echo "────────────────────────────────────────────────────"
echo ""
echo "1. ¿Sirve a Hansel AHORA?                    [ ] SÍ  [ ] NO"
echo "   Evidencia: ___________________________________"
echo ""
echo "2. ¿Mejora flujos REALES?                    [ ] SÍ  [ ] NO"
echo "   Workflow: $WORKFLOW"
echo "   Mejora específica: _________________________"
echo ""
echo "3. ¿Ahorra tiempo/tokens/dinero/errores?     [ ] SÍ  [ ] NO"
echo "   Estimado: _________________________________"
echo ""
echo "4. ¿Mejora calidad/memoria/búsqueda/ejec?    [ ] SÍ  [ ] NO"
echo "   Área: ______________________________________"
echo ""
echo "5. ¿Tiene uso a LARGO PLAZO?                 [ ] SÍ  [ ] NO"
echo "   Razón: _____________________________________"
echo ""
echo "6. ¿Es SEGURO, no rompe workflows activos?   [ ] SÍ  [ ] NO"
echo "   Riesgo: ____________________________________"
echo ""
echo "7. ¿Cuándo aplicar?                          [ ] AHORA  [ ] WATCHLIST  [ ] DESCARTAR"
echo "   Trigger si watchlist: _____________________"
echo ""
echo "────────────────────────────────────────────────────"
echo "  CLASIFICACIÓN FINAL"
echo "────────────────────────────────────────────────────"
echo ""
echo "[ ] INSTALAR_AHORA   — Todos los criterios cumplidos, riesgo bajo"
echo "[ ] PROBAR_SANDBOX   — Útil pero necesita validación"
echo "[ ] WATCHLIST        — Útil pero no ahora"
echo "[ ] DESCARTAR        — No conecta con flujos reales"
echo ""
echo "Razón: _____________________________________________"
echo ""
echo "════════════════════════════════════════════════════"
echo "  Guardar en: hansel-os/memory/decisions.json"
echo "  Si WATCHLIST: hansel-os/memory/watchlist.json"
echo "════════════════════════════════════════════════════"
